Option to reduce generated PDF file size
ovvn/dom-to-pdf pull request #9
Opened 2021-04-03 00:34 UTC by dvwright

Feature request. The PDF's being generated for me are often multi page and average ~ 42MB, this optional parameter if set, reduces them to ~ 1.4MB, without much loss of quality in my case. This PR implements my desired results. Thanks

2021-04-03 06:58 UTC, omazin requested changes

2021-04-03 06:58 UTC, omazin commented on README.md
> +* `reduceSize` - boolean, e.g. `true/false`, if set, the PDF created is MUCH smaller (up to 40x smaller) quality may be reduced as well. (the default is false)
I'd prefer having `compression` parameter
compression | string | compression of the generated JPEG, can have the values 'NONE', 'FAST', 'MEDIUM' and 'SLOW
-- | -- | --

2021-04-03 06:58 UTC, omazin commented on index.js
> +      if (reduceSize) {
with the `compression` parameter we get rid of the `if/else` and will have just
```javascript
pdf.addImage(imgData, 'PNG', 0, 0, a4Width, pageHeight, undefined, compression);
```

2021-04-03 06:58 UTC, omazin commented on index.js
> +  let reduceSize;
```javascript
let compression = 'NONE';
```

2021-04-03 07:00 UTC, ovvn commented
Hi @dvwright, thank you for the PR, please consider changes in the review.

2021-04-06 22:19 UTC, dvwright commented
Hi @ovvn great suggestions, implemented, thanks

2021-04-07 07:14 UTC, omazin approved these changes

2021-04-07 07:15 UTC, merged